# Generated by Django 5.1.7 on 2025-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('money', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
