# Generated by Django 5.1.7 on 2025-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0003_alter_player_money_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(default='123', max_length=300),
        ),
    ]
