# Generated by Django 5.1.7 on 2025-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0004_alter_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
