# Generated by Django 5.1.7 on 2025-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0005_alter_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='static/clicker/img/default.jpg', upload_to='static/clicker/img/'),
        ),
    ]
