# Generated by Django 5.1.7 on 2025-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0006_alter_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='money_per_click',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='money_per_sec',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
