# Generated by Django 5.1.7 on 2025-05-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0007_player_money_per_click_player_money_per_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='money_per_click',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='money_per_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='static/clicker/img/default.jpg', upload_to='static/clicker/img/'),
        ),
    ]
