# Generated by Django 5.1.7 on 2025-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0008_player_is_active_player_is_staff_player_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
