# Generated by Django 5.1.7 on 2025-06-01 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0009_alter_player_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('title', models.CharField(max_length=128, unique=True)),
                ('price', models.IntegerField()),
                ('mon_per_click', models.IntegerField()),
                ('mon_per_sec', models.IntegerField()),
                ('do_buy', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shop', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='money_per_click',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='money_per_sec',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
