# Generated by Django 5.1.7 on 2025-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0011_item_purchase_delete_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
