# Generated by Django 5.1.7 on 2025-06-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0012_player_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price', 'title']},
        ),
        migrations.AddField(
            model_name='item',
            name='emoji',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
