# Generated by Django 5.1.7 on 2025-06-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0013_alter_item_options_item_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='emoji',
        ),
    ]
