# Generated by Django 5.1.7 on 2025-06-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0014_remove_item_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
